version: "3.8"

services:
  backend:
    build: ./tournament-backend
    container_name: tournament-backend
    ports:
      - "5000:5000"
    env_file:
      - ./tournament-backend/.env
    environment:
      - NODE_ENV=production
      - PORT=5000
    networks:
      - tournament-network
    restart: always


  frontend:
    build: ./tournament-frontend
    container_name: tournament-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - tournament-network
    restart: always

networks:
  tournament-network:
    driver: bridge
